export enum GameStatus {
    START_GAME = "START_GAME",
    START_MATCH = "START_MATCH",
    DEAL_CARDS = "DEAL_CARDS",
    START_ROUND = "START_ROUND",
    START_TURN = "START_TURN",
    AWAIT_PLAYER_ACTION = "AWAIT_PLAYER_ACTION",
    END_TURN = "END_TURN",
    END_ROUND = "END_ROUND",
    END_MATCH = "END_MATCH",
    UPDATE_POINTS = "UPDATE_POINTS",
    END_GAME = "END_GAME"
}